spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/health_notification_db}
      auto-index-creation: true

  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:healthapp.healthyfittn@gmail.com}
    password: ${MAIL_PASSWORD:hpfkvmdfptifkuod}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
        transport:
          protocol: smtp
        debug: true
    test-connection: false

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8084
  error:
    include-message: always

fcm:
  credentials:
    path: ${FCM_CREDENTIALS_PATH:firebase-service-account.json}

notification:
  admin-email: ${ADMIN_EMAIL:healthapp.healthyfittn@gmail.com}

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.uuid}"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.healthapp.notification: ${APP_LOG_LEVEL:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"